import Navbar from "@/components/Navbar";
import "./globals.css";
import CustomComponent from "@/components/CustomComponent";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Navbar />
        <CustomComponent />
        <h1>Root Layout</h1>
        {children}
      </body>
    </html>
  );
}
